import type { Metadata } from 'next';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for Brand Kit Generator',
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
      <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

      <div className="prose prose-gray dark:prose-invert max-w-none space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>1. Acceptance of Terms</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              By accessing and using Brand Kit Generator (&quot;the Service&quot;), you accept and agree to be
              bound by these Terms of Service. If you do not agree to these terms, please do not use the
              Service.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>2. Description of Service</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              Brand Kit Generator is an AI-powered tool that creates brand identity packages including logos,
              color palettes, typography recommendations, and taglines based on user inputs.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>3. AI-Generated Content Disclaimer</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="bg-yellow-50 dark:bg-yellow-950 border-l-4 border-yellow-400 p-4">
              <p className="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">
                ⚠️ Important Notice About AI-Generated Assets
              </p>
              <ul className="list-disc list-inside text-yellow-700 dark:text-yellow-300 ml-4 space-y-1">
                <li>All assets are generated by artificial intelligence</li>
                <li>Content should be reviewed before commercial use</li>
                <li>Check for trademark conflicts</li>
                <li>Ensure compliance with your industry regulations</li>
                <li>We do not guarantee uniqueness of generated assets</li>
                <li>Similar prompts may produce similar results</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>4. Intellectual Property Rights</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h3 className="font-semibold mb-2">4.1 Generated Assets</h3>
              <p className="text-muted-foreground">
                You retain all rights to the generated brand kit assets. However, we make no guarantees about
                the originality or uniqueness of AI-generated content.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">4.2 Service Content</h3>
              <p className="text-muted-foreground">
                The Service itself, including its design, code, and functionality, is owned by Brand Kit
                Generator and is protected by copyright and other intellectual property laws.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">4.3 Third-Party Services</h3>
              <p className="text-muted-foreground">
                Generated assets use third-party services (Hugging Face for AI generation, Google Fonts for
                typography). These services have their own terms and licenses.
              </p>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>5. User Responsibilities</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">You agree to:</p>
            <ul className="list-disc list-inside text-muted-foreground ml-4">
              <li>Provide accurate and lawful information</li>
              <li>Not use the Service for illegal purposes</li>
              <li>Not attempt to reverse engineer or exploit the Service</li>
              <li>Verify trademark availability before commercial use</li>
              <li>Comply with all applicable laws and regulations</li>
              <li>Not submit offensive, harmful, or inappropriate content</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>6. Acceptable Use Policy</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">You may NOT use the Service to:</p>
            <ul className="list-disc list-inside text-muted-foreground ml-4">
              <li>Generate content that infringes on third-party trademarks</li>
              <li>Create misleading or deceptive brand identities</li>
              <li>Abuse or overload the Service with excessive requests</li>
              <li>Violate any laws or regulations</li>
              <li>Generate offensive, hateful, or inappropriate content</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>7. Disclaimer of Warranties</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
              KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
            </p>
            <ul className="list-disc list-inside text-muted-foreground ml-4">
              <li>Accuracy, reliability, or quality of generated content</li>
              <li>Uniqueness or originality of AI-generated assets</li>
              <li>Suitability for any particular purpose</li>
              <li>Freedom from errors, bugs, or interruptions</li>
              <li>Trademark or copyright clearance</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>8. Limitation of Liability</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, BRAND KIT GENERATOR SHALL NOT BE LIABLE FOR ANY:
            </p>
            <ul className="list-disc list-inside text-muted-foreground ml-4">
              <li>Indirect, incidental, special, or consequential damages</li>
              <li>Loss of profits, revenue, or business opportunities</li>
              <li>Trademark or copyright infringement claims</li>
              <li>Damages arising from use of generated assets</li>
              <li>Third-party claims related to generated content</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>9. Indemnification</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              You agree to indemnify and hold harmless Brand Kit Generator from any claims, damages, or
              expenses arising from:
            </p>
            <ul className="list-disc list-inside text-muted-foreground ml-4">
              <li>Your use of the Service</li>
              <li>Your use of generated assets</li>
              <li>Violation of these Terms</li>
              <li>Infringement of third-party rights</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>10. Service Availability</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              We do not guarantee uninterrupted access to the Service. We may:
            </p>
            <ul className="list-disc list-inside text-muted-foreground ml-4">
              <li>Suspend or terminate the Service at any time</li>
              <li>Modify features without notice</li>
              <li>Implement rate limits or usage restrictions</li>
              <li>Perform maintenance that affects availability</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>11. Free Service Notice</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              Brand Kit Generator is currently provided free of charge. We reserve the right to:
            </p>
            <ul className="list-disc list-inside text-muted-foreground ml-4">
              <li>Introduce paid features or subscriptions in the future</li>
              <li>Limit free tier usage</li>
              <li>Modify pricing at any time with notice</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>12. Modifications to Terms</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              We reserve the right to modify these Terms at any time. Continued use of the Service after
              changes constitutes acceptance of the new Terms.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>13. Governing Law</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction - To Be Added], without regard to its conflict of law provisions.
            </p>
            <p className="text-xs text-muted-foreground mt-2">
              Common jurisdictions: Delaware (USA), England and Wales (UK), or your local jurisdiction.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>14. Dispute Resolution</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              Any disputes arising from these Terms or use of the Service shall be resolved through binding
              arbitration, except where prohibited by law.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>15. Contact Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              For questions about these Terms, please contact us at:
            </p>
            <p className="text-muted-foreground font-mono text-sm">
              Email: legal@brandkitgenerator.com
              <br />
              Mailing Address: Brand Kit Generator
              <br />
              [Company Address - To Be Added]
              <br />
              [City, State ZIP Code]
            </p>
            <p className="text-xs text-muted-foreground mt-4">
              Note: Please update contact information and jurisdiction before deploying to production.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>16. Severability</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              If any provision of these Terms is found to be unenforceable, the remaining provisions will
              continue in full force and effect.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
